#!/bin/sh

while true; do
	action="$(printf '%s\n' \
		'Brightness' \
		'Screenshot' \
		'Lock Screen' | \
		dmenu -i -l "$DMENULINENUM")"

	[ -z "$action" ] && exit 1
	
	case "$action" in
		Brightness)
			dmenu_brightness && exit 0
		;;
		Screenshot)
			dmenu_screenshot && exit 0
		;;
		'Lock Screen')
			slock && exit 0
		;;
	esac 
done
