# /etc/bash/bashrc (Artix) | /etc/bash.bashrc (Arch)

case "$-" in
	*i*);;
	*)
		return
	;;
esac

PS1='$PWD \$ '
PATH=$PATH:
CDPATH=..:$HOME
EDITOR=/usr/bin/ex
VISUAL=/usr/bin/vi
PAGER=/bin/less
SYSTEMD_PAGER=
export PATH CDPATH EDITOR VISUAL PAGER SYSTEMD_PAGER

alias ls='ls -F --color=auto'
alias ll='ls -hl'
alias grep='grep --color=auto'
alias which='which 2>/dev/null'
alias ip='ip -c'
alias copy='clipboard.sh copy'
alias paste='clipboard.sh paste'

HISTCONTROL=ignoredups:erasedups
# Combine history across TTYs
#PROMPT_COMMAND='history -a; history -c; history -r'

_ps() {
	case "$1" in
		cpu|pcpu|'')
			ps axo pid,command,pcpu,pmem --sort=pcpu
		;;
		mem|pmem)
			ps axo pid,command,pcpu,pmem --sort=pmem
		;;
		*)
			ps "$@"
		;;
	# Hide kernel processes
	esac | grep -Fv \[
}

# $HOME/downloads is used instead but this directory keeps spawning
rmdir "$HOME"/Downloads 2>/dev/null

[ -f "$HOME"/.bashrc ] && . "$HOME"/.bashrc
